from .home.beranda import WelcomeCard
from .home.beranda import CompanyValue
from .home.beranda import ValueDescription
from .home.beranda import TrustedBrand
from .home.beranda import Testimonial
from .home.beranda import FAQ
from .home.about import About
from .home.tim import Tim
from .home.user import User
