# Generated by Django 5.1.2 on 2024-11-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unixni', '0002_companyvalue_valuedescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvalue',
            name='abbreviation',
            field=models.CharField(max_length=2),
        ),
    ]
