# Generated by Django 5.1.2 on 2024-11-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unixni', '0003_alter_companyvalue_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='trusted_brands/')),
            ],
        ),
        migrations.RenameField(
            model_name='valuedescription',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='valuedescription',
            name='title2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valuedescription',
            name='title3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valuedescription',
            name='title4',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
