# Generated by Django 5.1.2 on 2024-11-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unixni', '0004_trustedbrand_rename_title_valuedescription_title1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('testimonial_text', models.TextField(verbose_name='Testimoni')),
                ('image', models.ImageField(upload_to='testimonials/', verbose_name='Gambar')),
            ],
        ),
    ]
