# Generated by Django 5.1.2 on 2024-11-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unixni', '0006_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('line', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='about/')),
                ('description', models.TextField()),
                ('title2', models.CharField(max_length=255)),
                ('subtitle2', models.CharField(max_length=255)),
                ('description2', models.TextField()),
                ('subtitle3', models.CharField(max_length=255)),
                ('description3', models.TextField()),
                ('title3', models.CharField(max_length=255)),
                ('description4', models.TextField()),
                ('title4', models.CharField(max_length=255)),
                ('description5', models.TextField()),
                ('title5', models.CharField(max_length=255)),
                ('diagram', models.ImageField(upload_to='about/')),
                ('title6', models.CharField(max_length=255)),
                ('description6', models.TextField()),
                ('title7', models.CharField(max_length=255)),
                ('description7', models.TextField()),
            ],
        ),
    ]
