# Generated by Django 5.1.2 on 2024-11-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unixni', '0008_mission_structur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='list',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='structur',
            name='list',
            field=models.CharField(max_length=255),
        ),
    ]
