# Generated by Django 5.1.2 on 2024-11-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unixni', '0009_alter_mission_list_alter_structur_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('line', models.CharField(max_length=255)),
                ('profil', models.ImageField(upload_to='tim/')),
                ('title2', models.CharField(max_length=255)),
                ('subtitle2', models.CharField(max_length=255)),
                ('description1', models.TextField()),
                ('subtitle3', models.CharField(max_length=255)),
                ('description2', models.TextField()),
                ('title3', models.CharField(max_length=255)),
                ('description3', models.TextField()),
            ],
        ),
    ]
