# Generated by Django 5.1.2 on 2024-11-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unixni', '0010_tim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pencapaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='tim',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='tim',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='tim',
            name='description3',
        ),
    ]
