# Generated by Django 5.1.2 on 2024-11-18 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unixni', '0011_pencapaian_target_value_remove_tim_description1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GaleriUtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('line', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GaleriItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galeri/')),
                ('date', models.DateField()),
                ('galeri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='unixni.galeri')),
            ],
        ),
    ]
